name: CI with SonarQube (Azure VM) & Snyk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scan (Azure VM)
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          args: >
            -Dsonar.projectKey=portfolio-ci
            -Dsonar.organization=mayaworld13
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Snyk Scan (Docker Image)
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.DOCKER_IMAGE }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
